### ISSUE TITLE
Ploting

### ISSUE THREAD

**Issue by jeevanu** [QData/spacetimeformer#15]
How to save the plot offline without using wandb

**Comment by jakegrigsby** [comment]
There's not a great way to do this built in, because I used wandb from the beginning. Simplest way to do this I can think off is to make sure you installed the repo as editable (`pip install -e .`) and then change the code where it is saved to the wandb logger to instead save to disk:
https://github.com/QData/spacetimeformer/blob/efff49aea19eb9d6f6643aafa4916aa387893d84/spacetimeformer/plot.py#L92-L97
