### ISSUE TITLE
How is the relationship between variables in different Spaces measured

### ISSUE THREAD

**Issue by SingleXuu** [QData/spacetimeformer#24]
How is the relationship between variables in different Spaces measured？

I don't understand what this line of code does

x = val_time_emb + space_emb

Do you have any Chinese communication groups or documents？

**Comment by jakegrigsby** [comment]
The relationships between the variables are learned during the training process because we try to avoid using pre-defined variable graphs. We use "variable embeddings" to show which variable each token is from, and the attention mechanism can adjust the way information is passed between variables. Those embeddings are vectors of dim `d_model` and they are randomly initialized... it's implemented a lot like position embeddings or word embeddings in NLP if that helps explain it. The line of code you're referencing is when the variable embeddings are added to the embedding of the value of that variable at a particular time. So the final `d_model` size vector that is given to the Transformer is a combination of value, time and variable information.

Sorry, we don't have any Chinese communication or official documents... but we might be able to get some help from my co-author (@zhexjtu) if you have a question or specific section of the paper that needs translating/explanation.
