### ISSUE TITLE
Using the model to inference

### ISSUE THREAD

**Issue by threadthreasher** [QData/spacetimeformer#5]
Hi,

Thank you for this module.
Is there an example for inferencing?
I tried adding self.save_hyperparameters() to the Spacetimeformer_Forecaster init and then using the checkpoint as below but this requires x_c, y_c, x_t and y_t.
 Shouldn't inference only need the context and not the target? Is there some other step that I need to take to produce a model that can be used to inference?

```
    model = Spacetimeformer_Forecaster.load_from_checkpoint(checkpoint_path=checkpoint_path)
```

Thank you for your help.

**Comment by jakegrigsby** [comment]
Hi, I'll try to make some changes to make inference easier as soon as I can. This is not implemented because all of the research datasets have target values and they're used for training. The y_t arg should be optional... there is also some confusing variable re-arrangement that is the result of using the Informer forward pass signature ("x_enc", "x_mark_dec", ....) from a long time ago.

In the meantime you could get around this by passing in a zero vector that's the right shape (batch_size, target_sequence_length, number_of_variables). This should let the forward pass run as normal. The input to the decoder is made by taking the last few tokens of the context sequence and filling in the rest with zeros anyway:

https://github.com/QData/spacetimeformer/blob/90721a11906874027b3ac658a27fbbfde3150e9d/spacetimeformer/spacetimeformer_model/spacetimeformer_model.py#L178-L193

The real y_t values are then used to compute the loss. 

Note that x_t is required and that's intentional. We supply the timesteps we want to predict. If the dataset you're using doesn't have meaningful x values then x_c and x_t could also be zero vectors. The embedding adds arbitrary index ints as a time feature:
https://github.com/QData/spacetimeformer/blob/90721a11906874027b3ac658a27fbbfde3150e9d/spacetimeformer/spacetimeformer_model/nn/embed.py#L127-L130

**Comment by threadthreasher** [comment]
Thank you for the reply.
About batch size. Why would you need to supply all the batches that you train with at inference time? 
Isn't the prediction only made on the last batch?

**Comment by jakegrigsby** [comment]
No you shouldn't need to provide the train batches. If you're training on historical data and doing inference to predict the future based on the most recent timesteps, I guess your inference batch size will usually be 1. The benchmark datasets split the last 20-30% of the entire dataset into a test set and we make inference passes on all the slices of those timesteps, so the batch size is larger. 

Sorry I'm not sure I'm following the 32x32x3 question. The inputs are usually formatted as (timesteps, variables) and then the model flattens that into a sequence that is (timesteps * variables,).

**Comment by threadthreasher** [comment]
My mistake on the second question. Your explanation makes perfect sense. Thank you.
