### ISSUE TITLE
Issue while loading a model

### ISSUE THREAD

**Issue by jgcb00** [QData/spacetimeformer#51]
Hi,
After the training I'm trying to save the model and load it from the checkpoint.
But I got mismatch size error, so I tried to load the data as soon as the training is over.
But I still have the issue.
It looks like that it's the same issue as #13  .

The code :
```
    # Test from the code
    trainer.test(datamodule=data_module, ckpt_path="best")
    #Added only these two line
    trainer.save_checkpoint("best.ckpt")
    forecaster = forecaster.load_from_checkpoint(checkpoint_path="best.ckpt")
```

And I got a LOT of size mismatch

```
RuntimeError: Error(s) in loading state_dict for Spacetimeformer_Forecaster:
	size mismatch for spacetimeformer.enc_embedding.x_emb.embed_weight: copying a param with shape torch.Size([7, 6]) from checkpoint, the shape in current model is torch.Size([5, 6]).
	size mismatch for spacetimeformer.enc_embedding.y_emb.weight: copying a param with shape torch.Size([512, 43]) from checkpoint, the shape in current model is torch.Size([512, 31]).
	size mismatch for spacetimeformer.enc_embedding.var_emb.weight: copying a param with shape torch.Size([18, 512]) from checkpoint, the shape in current model is torch.Size([1, 512]).
	size mismatch for spacetimeformer.dec_embedding.x_emb.embed_weight: copying a param with shape torch.Size([7, 6]) from checkpoint, the shape in current model is torch.Size([5, 6]).
	size mismatch for spacetimeformer.dec_embedding.y_emb.weight: copying a param with shape torch.Size([512, 43]) from checkpoint, the shape in current model is torch.Size([512, 31]).
	size mismatch for spacetimeformer.dec_embedding.var_emb.weight: copying a param with shape torch.Size([18, 512]) from checkpoint, the shape in current model is torch.Size([1, 512]).
	size mismatch for spacetimeformer.classifier.weight: copying a param with shape torch.Size([18, 512]) from checkpoint, the shape in current model is torch.Size([1, 512]).
	size mismatch for spacetimeformer.classifier.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([1]).
```

What am I doing wrong ?

Also I didn't get what does the `--start_token_len` does ?
```
Length of decoder start token. Adds this many of the final context points to the start of the target sequence.
```
For example if I have one data every hour, and `start_token_len`  = 3, it will predict for the 3 hours from now ? And train to predict this value ?

Best Regards ! And thanks for the model !

**Comment by jakegrigsby** [comment]
Hey @jgcb00, yeah model saving/loading was broken because the model objects were not saving their kwargs to reinitialize to the correct shape. This should be one of the things fixed in the large update I just merged (sorry you'll probably have to retrain). I've tested this several times on most of the model types.

The start_token_len is a legacy feature from Informer where the last `start_token_len` timesteps of the context sequence are concatenated to the target sequence. This is somewhat similar to a start token in NLP and probably helped a bit by reducing the importance of cross attention. I stopped using this with new implementation details and saw no decrease in results. The default is now 0 and you can probably ignore it. The forecast duration you're thinking of is `--target_points` which determines how long the target sequence we're forecasting will be.

**Comment by jgcb00** [comment]
Hi @jakegrigsby , I'm going to try this tonight, I will keep my update there ! Thank you very much !

**Comment by jgcb00** [comment]
Indeed this update solved the issue ! 

Thank you very much !
