### ISSUE TITLE
Questions about Global-Attention and Decoder Fast-Attention

### ISSUE THREAD

**Issue by ShuAiii** [QData/spacetimeformer#57]
Thanks for uploading the code. This is a very interesting project!

I have a few questions surrounding some implementation details.

**1) Global-Attention**
 What is the purpose of `WindowTime` function and how does it help facilitate the concept of "Global-attention"?

**2) Decoder Fast-Attention**
When the `Performer` option is selected, the `FastAttention` for decoder self-attention is not instantiated with the `causal` flag set to `True`. This results in the attention mechanism of the forecast sequence attending to future tokens. Is this issue being addressed somewhere else?

**Comment by jakegrigsby** [comment]
Thanks!

1)  "Global attention" means "connecting each variable at a timestep to every other variable at every other timestep" (so var * time densely connected graph). The windowing functions give the option to split the graph into "windows" by time to reduce computation. So instead of connecting every variable at every timestep you could connect it to half the timesteps or a quarter and so on. It's pretty much a direct translation of Swin Transformer (https://arxiv.org/abs/2103.14030) to the time series case. Note that it's turned off by default and all those functions aren't doing anything.


2) `causal` can be False because there isn't anything to hide or mask from the decoder sequence. Standard NLP generative models need to mask tokens because they risk leaking the correct answer from the next timestep in the sequence. However we predict the entire target sequence in one forward pass from a sequence of arbitrary zero vectors so there is nothing to worry about. This is convenient because there are some fast attention implementations that struggle with causal masking.

**Comment by ShuAiii** [comment]
> Thanks!
> 
> 1. "Global attention" means "connecting each variable at a timestep to every other variable at every other timestep" (so var * time densely connected graph). The windowing functions give the option to split the graph into "windows" by time to reduce computation. So instead of connecting every variable at every timestep you could connect it to half the timesteps or a quarter and so on. It's pretty much a direct translation of Swin Transformer (https://arxiv.org/abs/2103.14030) to the time series case. Note that it's turned off by default and all those functions aren't doing anything.
> 2. `causal` can be False because there isn't anything to hide or mask from the decoder sequence. Standard NLP generative models need to mask tokens because they risk leaking the correct answer from the next timestep in the sequence. However we predict the entire target sequence in one forward pass from a sequence of arbitrary zero vectors so there is nothing to worry about. This is convenient because there are some fast attention implementations that struggle with causal masking.

Thanks for the explanation, I can confirm **2.** works. Closing the issue now!
