### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by LeftAttention** [QData/spacetimeformer#7]
Could you please share ```precip``` and ```asos``` datasets? I am very curious to test this model on these datasets.

**Comment by jakegrigsby** [comment]
The `asos` dataset should already be provided (?). It's `data/temperature-v1.csv` and the training script should find it. You should be able to get the precip dataset from [this google drive link](https://drive.google.com/drive/folders/1NcCIjuWbkvAi1MZUpYBIr7eYhaowvU7B?usp=sharing). Place the `usgs_precipitation` folder in `spacetimeformer/data/`. 

Fair warning: the Precip task is pretty difficult and we did not include the results in the paper; I thought it was interesting and already had all the code for it so I kept it in this release. This could be because of a bug in the dataset loading, or possibly because the "radar" configuration is too spaced out. Please let me know if you find anything!

**Comment by LeftAttention** [comment]
Thank you so much.
