### ISSUE TITLE
ValueError: Found array with dim 3. StandardScaler expected <= 2

### ISSUE THREAD

**Issue by guoxiaofan980520** [QData/spacetimeformer#8]
When I just followed the README and ran "python train.py spacetimeformer asos --context_points 160 --target_points 40 --start_token_len 8 --grad_clip_norm 1 --gpus 0 --batch_size 128 --d_model 200 --d_ff 800 --enc_layers 3 --dec_layers 3 --local_self_attn none --local_cross_attn none --l2_coeff .01 --dropout_emb .1 --run_name temporal_asos_160-40-nll --loss nll --time_resolution 1 --dropout_ff .2 --n_heads 8 --trials 3 --embed_method temporal --early_stopping --attn_plot --plot", I got the following error:
`ValueError: Found array with dim 3. StandardScaler expected <= 2`

**Comment by jakegrigsby** [comment]
This is an annoying scikit-learn versioning error. Try **scikit-learn==0.23.2**. It's complaining when we do inverse normalization for accuracy statistics, because predictions have a batch dimension. The normalization still works with broadcasting but eventually scikit-learn added a check to prevent this (https://github.com/scikit-learn/scikit-learn/blob/7ec440022ddb92b08d0ec1a17a074f2db23ae0f3/sklearn/utils/validation.py#L594). This is in the requirements.txt file but I'll add this to the list of updates for version 2. We will probably re-implement a simpler version of StandardScaler outside of scikit-learn.

**Comment by guoxiaofan980520** [comment]
> This is an annoying scikit-learn versioning error. Try **scikit-learn==0.23.2**. It's complaining when we do inverse normalization for accuracy statistics, because predictions have a batch dimension. The normalization still works with broadcasting but eventually scikit-learn added a check to prevent this (https://github.com/scikit-learn/scikit-learn/blob/7ec440022ddb92b08d0ec1a17a074f2db23ae0f3/sklearn/utils/validation.py#L594). This is in the requirements.txt file but I'll add this to the list of updates for version 2. We will probably re-implement a simpler version of StandardScaler outside of scikit-learn.

Thanks for your reply!
